# Generated by Django 4.0.5 on 2022-06-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='anio_de_nacimiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
