# Generated by Django 4.0.5 on 2022-06-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=20)),
                ('dia_y_horario', models.CharField(max_length=50)),
            ],
        ),
    ]
